const dashboard = [
  {
    id: 1,
    firstName: "Mike ",
    lastName: "Huston",
    email: "mikehuston@live.com",
    countryCode: 19,
    phone: 2364587,
    company: "Alibaba Traders.co",
    position: "Product Manager",
  },
  {
    id: 2,
    firstName: "Amazonia",
    lastName: "",
    email: "amazonia @live.com",
    countryCode: 1,
    phone: 4522558,
    company: "Amazonia Online",
    position: "Team Leader",
  },
  {
    id: 3,
    firstName: "Jennifer ",
    lastName: "Pattrick",
    email: "jenniferpatrick@live.com",
    countryCode: 91,
    phone: 2364587,
    company: "Jennifer Traders.ltd",
    position: "Product Manager",
  },
  {
    id: 4,
    firstName: "Robert",
    lastName: "Mike",
    email: "robermike@live.com",
    countryCode: 69,
    phone: 2364588,
    company: "Turag teev ltd.",
    position: "Ceo",
  },
  {
    id: 5,
    firstName: "Joey",
    lastName: "Clause",
    email: "joeyclause@live.com",
    countryCode: 69,
    phone: 2364587,
    company: "Dhaka Textile",
    position: "Manager",
  },
];

export default dashboard;
